// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TvMaze.Infrastructure.Data;

namespace TvMaze.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TvMazeDbContext))]
    [Migration("20201213141610_Version1")]
    partial class Version1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("TvMaze.Core.Entity.Cast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("Name")
                        .HasMaxLength(1024);

                    b.Property<int>("ShowId");

                    b.HasKey("Id");

                    b.HasIndex("ShowId");

                    b.ToTable("Cast");
                });

            modelBuilder.Entity("TvMaze.Core.Entity.Show", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasMaxLength(1024);

                    b.HasKey("Id");

                    b.ToTable("Show");
                });

            modelBuilder.Entity("TvMaze.Core.Entity.Cast", b =>
                {
                    b.HasOne("TvMaze.Core.Entity.Show", "Show")
                        .WithMany("Casts")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
